import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/custom/navbar";
import { AppContextProvider } from "@/context/AppContextProvider";
import SideBar from "@/components/custom/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "NOTES APP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet"></link>
      </head>
      <body className="min-h-full flex flex-col poppins-regular selection:bg-gray-950 selection:text-white">
        <AppContextProvider>
          <NavBar />

          <main className="h-[90vh] flex flex-row px-1 pt-6 md:px-10">

            {/* Left side navigation */}
            {/* <aside className="bg-teal-200 h-full w-[20%] p-2 md:p-2 border-r-2 overflow-hidden"> */}
              <SideBar />
            {/* </aside> */}

            {/* right side section */}
            <section className="h-full w-full p-2 md:px-30 md:py-10 md:w-[80%] z-10 overflow-y-scroll no-scrollbar">
              {children}
            </section>
          </main>

        </AppContextProvider>
      </body>
    </html>
  );
}
