import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/Components/NavBar";
import SideBar from "@/Components/SideBar";
import Hamburger from "@/Components/Hamburger";
import Script from "next/script";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Build - SAP Blogs",
  description: "A SAP Fiori UI5 and CAPM Blog Page generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar/>
        <div className="mainPage">

          <section className="left">
            <SideBar />
            <Hamburger />
            <p className="contents">Contents</p>
          </section>
          
          <section className="right">
            {children}
          </section>

        </div>

        <Script src="https://kit.fontawesome.com/9fa326583e.js" crossOrigin="anonymous"></Script>
      </body>
    </html>
  );
}
